- id: doi:10.1093/bioinformatics/btac582
  type: paper
  description: "propeller: testing for differences in cell type proportions in single cell data. Novel statistical methods for analyzing single-cell RNA-seq data with biological replication, addressing the challenges of experimental design in single-cell genomics."
  date: "2022-10-14"
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/phipsonlab/speckle
    - type: website
      link: https://phipsonlab.github.io/propeller-paper-analysis/
  tags:
    - open science
    - collaboration
  repo: phipsonlab/speckle

- id: doi:10.1038/s41592-018-0253-2

- id: doi:10.1186/s13059-024-03229-3
  type: paper
  description: "SuperCellCyto: enabling efficient analysis of large scale cytometry datasets. An extension of the SuperCell R package tailored for cytometry data analysis, authored by Putri et al. (2024) in Genome Biology."
  date: "2024-04-08"
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/phipsonlab/SuperCellCyto
    - type: website
      link: https://phipsonlab.github.io/SuperCellCyto/
  tags:
    - open science
    - cytometry
    - software
  repo: phipsonlab/SuperCellCyto
