- id: doi:10.1093/bioinformatics/btac582
  type: paper
  description: "propeller: testing for differences in cell type proportions in single cell data. Novel statistical methods for analyzing single-cell RNA-seq data with biological replication, addressing the challenges of experimental design in single-cell genomics."
  date: "2022-10-14"
  buttons:
    - type: source
      text: Publication
      link: https://doi.org/10.1093/bioinformatics/btac582
    - type: website
      link: https://github.com/phipsonlab/speckle
  tags:
    - software
    - single-cell
  repo: phipsonlab/speckle

- id: doi:10.1186/s13059-024-03229-3
  type: paper
  description: "SuperCellCyto: enabling efficient analysis of large scale cytometry datasets. An extension of the SuperCell R package tailored for cytometry data analysis, authored by Putri et al. (2024) in Genome Biology."
  date: "2024-04-08"
  buttons:
    - type: source
      text: Publication
      link: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03229-3
    - type: website
      link: https://github.com/phipsonlab/SuperCellCyto
  tags:
    - cytometry
    - software
  repo: phipsonlab/SuperCellCyto
