name: on-push
run-name: on push to main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# keep runs from piling up per branch
concurrency:
  group: on-push-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-citations:
    # skip first run because nothing enabled or setup yet
    if: github.run_number != 1
    uses: ./.github/workflows/update-citations.yaml

  build-site:
    needs: update-citations
    uses: ./.github/workflows/build-site.yaml
